### ISSUE TITLE
Way to disable Drag and Drop dynamically after initialising with a non null itemTypeBuilder

### ISSUE THREAD

**Issue by iancuio** [canopas/compose-recyclerview#16]
Hello!

I have the following use case:

A variable isDragAndDropEnabled which is true by default.
In certain cases, this will become false and drag and drop functionality on the RecyclerView should be disabled.
Problem is, I can't get it working.

What I have tried:

**I see in the documentation that:**

> Note: To enable drag-and-drop functionality, passing a non-null itemTypeBuilder is mandatory.

What I have tried:
**1) Passing a null `itemTypeBuilder` to `ComposeRecyclerView`**
```
        itemTypeBuilder =
        when (isDragAndDropEnabled) {
            true -> {
                object : ComposeRecyclerViewAdapter.ItemTypeBuilder {
                    override fun getItemType(position: Int): Int {
                        // Determine the item type based on the position
                        // Customize this logic based on your requirements
                        return 0
                    }
                }
            }

            false -> {
                null
            }
        }
```

**2) Changing `isLongPressDragEnabled` upon recomposition to true/false.**

```
        itemTouchHelperConfig =
            when(isDragAndDropEnabled) {
                true -> {
                    {
                        isLongPressDragEnabled = true
                        swipeDirs = null
                        dragDirs = null
                    }
                }
                false -> {
                    {
                        isLongPressDragEnabled = false
                        swipeDirs = null
                        dragDirs = null
                    }
                }
            }
```

I can confirm that these blocks are called upon recomposition, but the behaviour stays the same as it was initialized.

Is there any way to disable drag and drop dynamically?

Thank you in advance!

**Comment by cp-megh-l** [comment]
From version `1.0.5`, Passing a null itemTypeBuilder to ComposeRecyclerView will disable drag and drop
